### ISSUE TITLE
Why is MbUnit style tests discouraged?

### ISSUE THREAD

**Issue by jzabroski** [fixie/fixie.integration#2]
The comment in your PR from 2018 suggests that MbUnit and NUnit are very similar, but I don't think NUnit has support for MbUnit-style `[VerifyContract]` and features like its HashCodeVerifier

**Comment by plioi** [comment]
Good question! I'm not sure which PR that is, but I should probably clarify my intent. I'm sure I sounded like "MbUnit itself is to be discouraged", but that's not what I intended, now that I think about it.

Rather, a more general regret I have from early on in Fixie's life was my promoting it's ability to mimic other frameworks' features. In truth, that helped motivate me to provide useful customization hooks, but the hope would be that new patterns would then emerge, rather than merely imitating existing frameworks' features.

As a small project with a small following and a high barrier to entry for new contributors, I often have to weigh the utility of any given sample convention (like those that have survived in fixie.integration), against the weight of my maintaining them into the indefinite future. Given that, I'd rather wait for someone to say "Patrick, you're missing a vital customization hook right here!" than increasing fixie.integration's codebase with growing copies of other test frameworks' features.  I've kept around the current NUnit and xUnit imitations (each just a fraction of those frameworks' full feature sets), as they prove out the most fundamental test class lifecycle differences in a way that new users tend to recognize.

**Comment by jzabroski** [comment]
@plioi Thanks for following up!

Popularity takes time.  I remember for years not understanding why NUnit was so big, other than the fact that Roy Osherove wrote a dumb book called The Art of Unit Testing _that I absolutely hated the hell out of because it taught so many wrong principles for testing well_ and the fact the Microsoft seemed to use it a bit internally.

xUnit.net really took off for silly reasons - the xUnit.net Benchmark extension really helped it gain traction when .NET Core was taking off, and now most .NET Core projects use xUnit.net.  Even before this time, xUnit.net was "second best" to NUnit in popularity while still being the favorite among mocking framework authors like Moq and NSubstitute.
